INSERT INTO category_master (category_id, category, subcategory, owner_type, sort_order)
VALUES
    (1, 'Food', 'Dining', 'system', 10),
    (2, 'Food', 'Coffee', 'system', 20),
    (3, 'Food', 'Fast Food', 'system', 30),
    (4, 'Food', 'Delivery', 'system', 40),
    (5, 'Food', 'Groceries', 'system', 50),
    (6, 'Food', 'Warehouse', 'system', 60),
    (7, 'Housing', 'Rent', 'system', 110),
    (8, 'Housing', 'Mortgage', 'system', 120),
    (9, 'Housing', 'Condo Fees', 'system', 130),
    (10, 'Housing', 'Furniture', 'system', 140),
    (11, 'Housing', 'Home Improvement', 'system', 150),
    (12, 'Utilities', 'Hydro', 'system', 210),
    (13, 'Utilities', 'Gas', 'system', 220),
    (14, 'Utilities', 'Water', 'system', 230),
    (15, 'Utilities', 'Internet', 'system', 240),
    (16, 'Utilities', 'Phone', 'system', 250),
    (17, 'Transportation', 'Transit', 'system', 310),
    (18, 'Transportation', 'Parking', 'system', 320),
    (19, 'Transportation', 'Ride Share', 'system', 330),
    (20, 'Transportation', 'Fuel', 'system', 340),
    (21, 'Transportation', 'EV Charging', 'system', 350),
    (22, 'Auto', 'Insurance', 'system', 410),
    (23, 'Auto', 'Maintenance', 'system', 420),
    (24, 'Auto', 'Registration', 'system', 430),
    (25, 'Auto', 'Tires', 'system', 440),
    (26, 'Auto', 'Car Wash', 'system', 450),
    (27, 'Travel', 'Flights', 'system', 510),
    (28, 'Travel', 'Hotels', 'system', 520),
    (29, 'Travel', 'Local Transportation', 'system', 530),
    (30, 'Travel', 'Attractions', 'system', 540),
    (31, 'Travel', 'Travel Dining', 'system', 550),
    (32, 'Shopping', 'General', 'system', 610),
    (33, 'Shopping', 'Clothing', 'system', 620),
    (34, 'Shopping', 'Electronics', 'system', 630),
    (35, 'Shopping', 'Household', 'system', 640),
    (36, 'Shopping', 'Online Shopping', 'system', 650),
    (37, 'Health', 'Medical', 'system', 710),
    (38, 'Health', 'Dental', 'system', 720),
    (39, 'Health', 'Pharmacy', 'system', 730),
    (40, 'Health', 'Vision', 'system', 740),
    (41, 'Personal Care', 'Haircut', 'system', 810),
    (42, 'Personal Care', 'Skincare', 'system', 820),
    (43, 'Personal Care', 'Beauty', 'system', 830),
    (44, 'Personal Care', 'Fitness', 'system', 840),
    (45, 'Entertainment', 'Movies', 'system', 910),
    (46, 'Entertainment', 'Events', 'system', 920),
    (47, 'Entertainment', 'Games', 'system', 930),
    (48, 'Entertainment', 'Hobbies', 'system', 940),
    (49, 'Subscriptions', 'Streaming', 'system', 1010),
    (50, 'Subscriptions', 'Software', 'system', 1020),
    (51, 'Subscriptions', 'Membership', 'system', 1030),
    (52, 'Subscriptions', 'News', 'system', 1040),
    (53, 'Financial Fees', 'Bank Fee', 'system', 1110),
    (54, 'Financial Fees', 'FX Fee', 'system', 1120),
    (55, 'Financial Fees', 'Interest Charge', 'system', 1130),
    (56, 'Financial Fees', 'Service Fee', 'system', 1140),
    (57, 'Education', 'Tuition', 'system', 1210),
    (58, 'Education', 'Books', 'system', 1220),
    (59, 'Education', 'Courses', 'system', 1230),
    (60, 'Education', 'Certification', 'system', 1240),
    (61, 'Gifts', 'Gifts', 'system', 1310),
    (62, 'Gifts', 'Donations', 'system', 1320),
    (63, 'Gifts', 'Family Support', 'system', 1330),
    (64, 'Other', 'Miscellaneous', 'system', 1410),
    (65, 'Other', 'Uncategorized', 'system', 1420)
ON CONFLICT (category, subcategory, owner_type) DO NOTHING;
