from __future__ import annotations

FALLBACK_SPEND_TYPES = ["expense", "refund", "credit", "reimbursement"]
FALLBACK_INCOME_TYPES = ["income"]
IGNORED_MOVEMENT_TYPES = ["payment", "debt_payment", "transfer", "stored_value_reload", "ignored"]
REVIEW_TYPES = ["manual_review"]
FALLBACK_TRANSACTION_TYPES = [
    "expense",
    "refund",
    "credit",
    "income",
    "payment",
    "debt_payment",
    "transfer",
    "reimbursement",
    "stored_value_reload",
    "manual_review",
    "ignored",
    "zero",
]
SCOPES = ["personal", "shared"]

FALLBACK_TRANSACTION_TYPE_LABELS = {
    "expense": "Expense",
    "refund": "Refund",
    "credit": "Merchant Credit",
    "income": "Income",
    "payment": "Card Payment",
    "debt_payment": "Debt Payment",
    "transfer": "Internal Transfer",
    "reimbursement": "Reimbursement",
    "stored_value_reload": "Prepaid Card Reload",
    "manual_review": "Needs Review",
    "ignored": "Excluded",
    "zero": "Zero Amount",
}

TRANSACTION_TYPE_HELP = {
    "Expense": "Real spending that counts toward spend totals.",
    "Refund": "Merchant refund that reduces spending.",
    "Merchant Credit": "Statement credit or adjustment that reduces spending.",
    "Income": "True income, such as payroll, rent collected, interest, or tax refund.",
    "Card Payment": "Payment made to a credit card. Ignored for spending to avoid double counting.",
    "Debt Payment": "Cash leaving an account to pay a card, loan, or line of credit. Ignored for spending.",
    "Internal Transfer": "Money moved between your own accounts. Ignored for spending and income.",
    "Reimbursement": "Money paid back to you, or pass-through spending you do not want counted as your own spend.",
    "Prepaid Card Reload": "Large reload/top-up transaction, such as loading PayPower or another stored-value card. Ignored for spending.",
    "Needs Review": "Ambiguous transaction that needs a manual decision.",
    "Excluded": "Transaction intentionally excluded from spending and income reporting.",
    "Zero Amount": "Zero-dollar row.",
}

SCOPE_LABELS = {
    "personal": "Personal",
    "shared": "Shared",
}

COLUMN_LABELS = {
    "transaction_date": "Date",
    "posted_date": "Posted Date",
    "account_name": "Account",
    "institution": "Institution",
    "transaction_type": "Type",
    "scope": "Scope",
    "merchant_raw": "Raw Merchant",
    "merchant_clean": "Merchant",
    "category": "Category",
    "subcategory": "Subcategory",
    "amount": "Amount",
    "display_amount": "Amount",
    "source_file": "Source File",
    "source_id": "Source",
    "import_batch_id": "Import Batch",
    "file_hash": "File Hash",
    "row_number": "Row",
    "raw_data": "Raw Data",
    "row_hash": "Row Hash",
    "normalized_transaction_id": "Transaction ID",
    "old_category": "Old Category",
    "new_category": "New Category",
    "old_subcategory": "Old Subcategory",
    "new_subcategory": "New Subcategory",
    "old_transaction_type": "Old Type",
    "new_transaction_type": "New Type",
    "old_merchant_clean": "Old Merchant",
    "new_merchant_clean": "New Merchant",
    "matched_rule_id": "Matched Rule",
    "month": "Month",
    "gross_spend": "Gross Spend",
    "refunds_credits": "Refunds/Credits",
    "refund_credit_abs": "Refunds/Credits",
    "net_spend": "Personal Net Spend",
    "income": "Income",
    "income_amount": "Income",
    "card_payments": "Card Payments",
    "payment_amount": "Card Payments",
    "debt_payments": "Debt Payments",
    "debt_payment_amount": "Debt Payments",
    "transfers": "Internal Transfers",
    "transfer_amount": "Internal Transfers",
    "reimbursements": "Reimbursements",
    "reimbursement_amount": "Reimbursements",
    "stored_value_reloads": "Prepaid Card Reloads",
    "stored_value_reload_amount": "Prepaid Card Reloads",
    "manual_review": "Needs Review",
    "manual_review_amount": "Needs Review",
    "ignored_movement": "Excluded From Spend",
    "ignored_amount": "Excluded",
    "transactions": "Transactions",
    "file_net": "File Net",
    "first_date": "First Date",
    "last_date": "Last Date",
    "rows_seen": "Rows Seen",
    "rows_duplicate": "Duplicate Rows",
    "rows_failed": "Failed Rows",
    "rows_in_file": "Rows In File",
    "existing_duplicates": "Existing Duplicates",
    "new_rows": "New Rows",
    "statement_month": "Statement Month",
    "processed_name": "Processed Name",
    "gross_expenses": "Gross Expenses",
    "refunds_and_credits": "Refunds/Credits",
    "payments": "Card Payments",
    "debt_payments": "Debt Payments",
    "file_net_total": "File Net Total",
    "size_kb": "Size KB",
    "type": "File Type",
    "file": "File",
    "status": "Status",
    "rows_inserted": "Rows Inserted",
    "destination": "Destination",
    "error": "Error",
    "imported_at": "Imported At",
    "message": "Message",
}

DRILLDOWN_METRICS = [
    "Gross Spend",
    "Refunds/Credits",
    "Personal Net Spend",
    "Income",
    "Card Payments",
    "Debt Payments",
    "Internal Transfers",
    "Reimbursements",
    "Prepaid Card Reloads",
    "Needs Review",
    "Excluded From Spend",
]
